server:
  port: 8085

spring:
  application:
    #nacos会自动根据服务名拉取dataid对应的配置文件。如果dataid和服务名不一致就需要手动指定dataid\
    #跟服务名相同的dataid的配置文件，称之为默认的配置文件
    name: nacos-config
  #在配置中心： 可以通过profile进行设置
  #只有默认的配置文件(与服务名相同的配置文件)才能结合profile进行使用
  #对应的DataId:${spring.application.name}-${profile}.${file-extension:properties}
  #后缀必须跟随默认配置文件的格式来
  #配置文件的优先级，（优先级大的会覆盖优先级小的，并且会形成互补）
  #profile>默认配置文件>extension-configs（下标大的优先级高）>shared-configs共享配置文件（下标大的优先级高）
  profiles:
    active: dev
