server:
  port: 8076

spring:
  #应用名称，（nacos会将该名称当作服务名称）
  main:
    allow-bean-definition-overriding: true
  application:
    name: stock-seata-alibaba-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seata_stock?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        #这个是nacos页面的登录名，如果不设置，默认都是nacos
        username: nacos
        password: nacos
        #命名空间，可以隔离不同的生产环境，比如dev开发环境，prod生产环境,默认就是public
        namespace: public
        #fasle代表永久实例，哪怕宕机了也不会删除实例
        ephemeral: true
        #group: 默认是DEFAULT_GROUP 同一个命名空间中具有相同特征的服务进行归类
        #service: 默认是${spring.application.name}
        #weight: 权重 数值越大，权重越大
        #metadata: 假设元数据中有 version=1，那么可以结合元数据做扩展功能
#    #不使用ribbon
#    loadbalancer:
#      ribbon:
#        enabled: false
    seata:
      registry:
        #配置seata的注册中心，告诉seata client怎么去访问seataserver
        type: nacos
        nacos:
          server-addr: 127.0.0.1:8848
          #seata服务名
          application: seata-server
          username: nacos
          password: nacos
          #zeata server的分组，默认就是SEATA_GROUP
          group: SEATA_GROUP
      #配置中心
      config:
        type: nacos
        nacos:
          server-addr: 127.0.0.1:8848
          username: nacos
          password: nacos
          group: SEATA_GROUP
    sentinel:
      transport:
        dashboard: localhost:8858 # 指定控制台服务的地址
        # 默认是 8719，通过该端口使得平台于微服务的到通信
      web-context-unify: false #默认是true，即将调用链路收起来，不维护
      datasource:
        stock-flow-rule: #这个名字可以自定义的
          nacos:
            serverAddr: 127.0.0.1:8848
            #如果配置了权限管理，必须加用户名和密码
            username: nacos
            password: nacos
            dataId: stock-service-sentinel-flow-rule
            ruleType: flow
    alibaba:
      seata:
        tx-service-group: my_test_tx_group #配置事务分组
stock-seata-alibaba-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
#    自定义的配置均衡算法
#   NFLoadBalancerRuleClassName: org.kehl.ribbon.CustomRule
ribbon:
  eager-load:
    #配置服务提供者，使用ribbon的饥饿加载，多个的话使用逗号分隔
    clients: stock-seata-alibaba-service
    #开启饥饿加载
    enabled: true
#  springboot默认的日志级别是info，feign的debug日志级别就不会输出


#openfeign整合sentinel
feign:
  sentinel:
    enabled: true
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: org.kehl.entity